apiVersion: v1
kind: Service
metadata:
  name: faas-netesd
  namespace: openfaas
  labels:
    app: faas-netesd
spec:
  type: NodePort
  ports:
    - port: 8080
      protocol: TCP
      targetPort: 8080
      nodePort: 31111
  selector:
    app: faas-netesd
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: faas-controller
  namespace: openfaas
---
apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: faas-netesd
  namespace: openfaas
spec:
  replicas: 1
  selector:
    matchLabels:
      app: faas-netesd
  template:
    metadata:
      labels:
        app: faas-netesd
    spec:
      serviceAccountName: faas-controller
      containers:
      - name: faas-netesd
        image: functions/faas-netesd:0.3.3
        imagePullPolicy: Always
        env:
        - name: function_namespace
          value: openfaas-fn
        ports:
        - containerPort: 8080
          protocol: TCP
        resources:
          limits:
            memory: 1024Mi
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: faas-controller
rules:
- apiGroups:
  - ""
  resources:
  - services
  verbs:
  - get
  - list
  - watch
  - create
  - delete
  - update
- apiGroups:
  - extensions
  resources:
  - deployments
  verbs:
  - get
  - list
  - watch
  - create
  - delete
  - update
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: faas-controller
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: faas-controller
subjects:
- kind: ServiceAccount
  name: faas-controller
  namespace: openfaas
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: faas-controller-fn
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: faas-controller
subjects:
- kind: ServiceAccount
  name: faas-controller
  namespace: openfaas-fn
---
apiVersion: v1
kind: Service
metadata:
  name: gateway
  namespace: openfaas
  labels:
    app: gateway
spec:
  type: NodePort
  ports:
    - port: 8080
      protocol: TCP
      targetPort: 8080
      nodePort: 31112
  selector:
    app: gateway
---
apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: gateway
  namespace: openfaas
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gateway
  template:
    metadata:
      labels:
        app: gateway
    spec:
      containers:
      - name: gateway
        image: functions/gateway:0.6.7
        imagePullPolicy: Always
        env:
        - name: functions_provider_url
          value: "http://faas-netesd.openfaas:8080/"
        - name: faas_nats_address
          value: "nats.openfaas"
        - name: faas_nats_port
          value: "4222"
        - name: write_timeout
          value: "60"
        - name: read_timeout
          value: "60"
        ports:
        - containerPort: 8080
          protocol: TCP
        resources:
          limits:
            memory: 1024Mi

