apiVersion: v1
kind: Service
metadata:
  name: prometheus
  namespace: openfaas
  labels:
    app: prometheus
spec:
  type: ClusterIP
  ports:
    - port: 9090
      protocol: TCP
      targetPort: 9090
  selector:
    app: prometheus
---
apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: prometheus
  namespace: openfaas
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prometheus
  template:
    metadata:
      labels:
        app: prometheus
    spec:
      containers:
      - name: prometheus
        image: prom/prometheus:v1.8.2
        imagePullPolicy: Always
        command:
          - prometheus
          - -config.file=/etc/prometheus/prometheus.yml
          - -storage.local.path=/prometheus
          - --alertmanager.url=http://alertmanager.openfaas:9093
        ports:
        - containerPort: 9090
          protocol: TCP
        resources:
          limits:
            memory: 1Gi
        volumeMounts:
        - mountPath: /etc/prometheus/prometheus.yml
          name: prometheus-config
          subPath: prometheus.yml
        - mountPath: /etc/prometheus/alert.rules
          name: prometheus-config
          subPath: alert.rules
      volumes:
        - name: prometheus-config
          configMap:
            name: prometheus-config
            items:
              - key: prometheus.yml
                path: prometheus.yml
                mode: 0644
              - key: alert.rules
                path: alert.rules
                mode: 0644
---
apiVersion: v1
kind: Service
metadata:
  name: alertmanager
  namespace: openfaas
  labels:
    app: alertmanager
spec:
  type: ClusterIP
  ports:
    - port: 9093
      protocol: TCP
      targetPort: 9093
  selector:
    app: alertmanager
---
apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: alertmanager
  namespace: openfaas
spec:
  replicas: 1
  selector:
    matchLabels:
      app: alertmanager
  template:
    metadata:
      labels:
        app: alertmanager
    spec:
      containers:
      - name: alertmanager
        image: prom/alertmanager:v0.9.1
        imagePullPolicy: Always
        command:
          - alertmanager
          - -config.file=/alertmanager.yml
          - -storage.path=/alertmanager
        ports:
        - containerPort: 9093
          protocol: TCP
        resources:
          limits:
            memory: 128Mi
        volumeMounts:
        - mountPath: /alertmanager.yml
          name: alertmanager-config
          subPath: alertmanager.yml
      volumes:
        - name: alertmanager-config
          configMap:
            name: alertmanager-config
            items:
              - key: alertmanager.yml
                path: alertmanager.yml
                mode: 0644
---
kind: ConfigMap
apiVersion: v1
metadata:
  labels:
    app: prometheus
  name: prometheus-config
  namespace: openfaas
data:
  prometheus.yml: |
    global:
      scrape_interval:     15s
      evaluation_interval: 15s
      external_labels:
          monitor: 'faas-monitor'
    rule_files:
        - 'alert.rules'
    scrape_configs:
      - job_name: 'prometheus'
        scrape_interval: 5s
        static_configs:
          - targets: ['localhost:9090']
      - job_name: "gateway"
        scrape_interval: 5s
        dns_sd_configs:
          - names: ['gateway']
            port: 8080
            type: A
            refresh_interval: 5s
  alert.rules: |
    ALERT service_down
      IF up == 0
    ALERT APIHighInvocationRate
      IF sum ( rate(gateway_function_invocation_total{code="200"}[10s]) ) by (function_name) > 5
      FOR 5s
      LABELS {
        service = "gateway",
        severity = "major",
        value = "{{$value}}"
      }
      ANNOTATIONS {
        summary = "High invocation total on {{ $labels.instance }}",
        description =  "High invocation total on {{ $labels.instance }}"
      }
---
kind: ConfigMap
apiVersion: v1
metadata:
  labels:
    app: alertmanager
  name: alertmanager-config
  namespace: openfaas
data:
  alertmanager.yml: |
    route:
      group_by: ['alertname', 'cluster', 'service']
      group_wait: 5s
      group_interval: 10s
      repeat_interval: 30s
      receiver: scale-up
      routes:
      - match:
          service: gateway
          receiver: scale-up
          severity: major
    inhibit_rules:
    - source_match:
        severity: 'critical'
      target_match:
        severity: 'warning'
      equal: ['alertname', 'cluster', 'service']
    receivers:
    - name: 'scale-up'
      webhook_configs:
        - url: http://gateway.openfaas:8080/system/alert
          send_resolved: true
