---
kind: ConfigMap
apiVersion: v1
metadata:
  name: caddy-config
  namespace: openfaas
  labels:
    app: caddy
data:
  Caddyfile: |
    :80 {
        status 200 /healthz
        basicauth /system {$ADMIN_USER} {$ADMIN_PASSWORD}
        basicauth /ui {$ADMIN_USER} {$ADMIN_PASSWORD}
        proxy / gateway:8080 {
                transparent
            }

        errors stderr
        tls off
    }
