---
apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: gateway
  namespace: openfaas
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gateway
  template:
    metadata:
      labels:
        app: gateway
    spec:
      containers:
      - name: gateway
        image: functions/gateway:0.7.8
        imagePullPolicy: Always
        env:
        - name: faas_prometheus_host
          value: "prometheus.openfaas"
        - name: functions_provider_url
          value: "http://faas-netesd.openfaas:8080/"
        - name: faas_nats_address
          value: "nats.openfaas"
        - name: faas_nats_port
          value: "4222"
        - name: direct_functions
          value: "true"
        - name: direct_functions_suffix
          value: "openfaas-fn"
        - name: write_timeout
          value: "60s"
        - name: read_timeout
          value: "60s"
        - name: upstream_timeout 
          value: "55s"
        ports:
        - containerPort: 8080
          protocol: TCP
        resources:
          limits:
            memory: 1024Mi
