---
apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: faas-netesd
  namespace: openfaas
spec:
  replicas: 1
  selector:
    matchLabels:
      app: faas-netesd
  template:
    metadata:
      labels:
        app: faas-netesd
      annotations:
        prometheus.io.scrape: 'false'
    spec:
      serviceAccountName: faas-controller
      containers:
      - name: faas-netesd
        image: functions/faas-netesd:0.4.3
        imagePullPolicy: Always
        env:
        - name: function_namespace
          value: openfaas-fn
        - name: write_timeout
          value: "60"
        - name: read_timeout
          value: "60"
        ports:
        - containerPort: 8080
          protocol: TCP
        resources:
          limits:
            memory: 1024Mi
